# Generated by Django 2.0.7 on 2019-03-22 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20190318_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='picture',
        ),
    ]
