# Generated by Django 2.0.7 on 2019-03-22 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='courses_cajas',
            fields=[
                ('identificador', models.AutoField(primary_key=True, serialize=False)),
                ('certificada', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='courses_courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('cantidad', models.IntegerField()),
                ('tipo', models.CharField(max_length=100)),
                ('registradora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.courses_cajas')),
            ],
        ),
        migrations.CreateModel(
            name='courses_productos',
            fields=[
                ('identificador', models.AutoField(primary_key=True, serialize=False)),
                ('precio', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('fact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.courses_courses')),
            ],
        ),
        migrations.CreateModel(
            name='courses_tiendas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=140)),
            ],
        ),
        migrations.DeleteModel(
            name='producto',
        ),
        migrations.AddField(
            model_name='courses_cajas',
            name='tienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.courses_tiendas'),
        ),
    ]
